---
title: "Venn_diagram"
author: "Paloma"
date: "2024-11-29"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
Question 29

```{r warning=FALSE}

# Set working directory
```


```{r warning=FALSE}
# Load necessary libraries
library(venn)
library(eulerr)

# Load the data
data <- read.csv("./data/Q9_10_11_29_31_all.xlsx - Form Responses 1.csv")

# Install eulerr if not already installed
if (!requireNamespace("eulerr", quietly = TRUE)) {
  install.packages("eulerr")
}

# Clean and filter the relevant column
improvement_areas <- na.omit(data$Q29_ImprovementArea_categorical)

# Split categories (assuming they are comma-separated if multiple per response)
split_areas <- strsplit(as.character(improvement_areas), split = "/\\s*")

# Count the frequency of each category and overlap
quality  <- sum(sapply(split_areas, function(x) "quality" %in% x))
quantity <- sum(sapply(split_areas, function(x) "quantity" %in% x))
pressure <- sum(sapply(split_areas, function(x) "pressure" %in% x))
nothing <- sum(sapply(split_areas, function(x) "nothing" %in% x))
other <- sum(sapply(split_areas, function(x) "other" %in% x))
overlap <- sum(sapply(split_areas, function(x) all(c("quality", "pressure") %in% x)))
overlap3 <- sum(sapply(split_areas, function(x) all(c("quantity", "pressure") %in% x)))
overlap1  <- sum(sapply(split_areas, function(x) all(c("quality", "quantity") %in% x)))
overlap2 <- sum(sapply(split_areas, function(x) all(c("quality", "quantity", "pressure") %in% x)))

# Create a named list with the counts
area_counts <- c(
  "Quality" = quality,
    "Pressure" = pressure,
  "Quantity" = quantity,
  "Quality&Pressure" = overlap,
  "Quality&Quantity" = overlap1,
  "Quality&Quantity&Pressure" = overlap2,
  "Quantity&Pressure" = overlap3,
  "Nothing" = nothing
)

# Create the proportional Venn diagram
venn_diagram <- euler(area_counts)

```

```{r plot}

# Plot
# Plot the diagram

png(file= "./output/venn_diagram.png", width = 750, height = 700)

plot(venn_diagram, 
     fills = c("gold", "turquoise3", "coral1", "thistle"), 
     edges = list(col = "white", lex = 1.5),
     labels = list(size = 7, 
                   fontfamily = "RobotoCondensed-Semibold", 
                   fontsize = 18.5), 
     main = "Aspectos que necesitan ser mejorados",
     quantities = list(type = "percent", fontsize = 15.5))

dev.off()
```






